# Generated by Django 4.2.16 on 2026-09-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewritetask',
            name='llm_report',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rewritetask',
            name='protocol_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rewritetask',
            name='skill',
            field=models.CharField(default='humanizer', max_length=32),
        ),
        migrations.AddField(
            model_name='rewritetask',
            name='skill_version',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
