# Generated by Django 4.2.16 on 2026-09-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai', '0002_rewritetask_llm_report_rewritetask_protocol_ok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewritetask',
            name='cache_hit_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewritetask',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewritetask',
            name='cost_cny',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rewritetask',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
