# Generated by Django 4.2.16 on 2026-10-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai', '0003_rewritetask_cache_hit_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewritetask',
            name='llm_added_facts',
            field=models.TextField(blank=True, default=''),
        ),
    ]
