# Generated by Django 4.2.16 on 2026-10-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai', '0004_rewritetask_llm_added_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewritetask',
            name='intensity',
            field=models.CharField(default='medium', max_length=16),
        ),
    ]
