# Generated by Django 4.2.16 on 2026-10-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai', '0005_rewritetask_intensity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=40)),
                ('openid', models.CharField(db_index=True, max_length=64)),
                ('rating', models.CharField(choices=[('good', '满意'), ('bad', '不满意')], max_length=8)),
                ('reason', models.CharField(blank=True, default='', max_length=32)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deai_feedback',
                'unique_together': {('task_id', 'openid')},
            },
        ),
    ]
