# Generated by Django 4.2.16 on 2026-10-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewritetask',
            name='prompt_fingerprint',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
