# Generated by Django 4.2.16 on 2026-10-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai', '0007_rewritetask_prompt_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewritetask',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
