# Generated by Django 4.2.16 on 2026-10-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai', '0008_rewritetask_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('openid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deai_user_profile',
            },
        ),
    ]
