# Generated by Django 4.2.16 on 2026-10-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxAccessToken',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=512)),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deai_wx_access_token',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_masked',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
