# Generated by Django 4.2.16 on 2026-10-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai', '0010_phone_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewritetask',
            name='cost_source',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
